# Release code in the master branch to PyPi

stages:
- stage: Publish_on_TestPyPi
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
      displayName: 'Use Python 3.7'

    - script: |
        pip install twine

    # Build the python distribution from source
    - script: |
        pip install -r requirements.txt
        ./tools/package.sh

    - task: TwineAuthenticate@1
      displayName: 'Twine Authenticate'
      inputs:
        pythonUploadServiceConnection: testpypi

    # Use command line script to 'twine upload', use -r to pass the repository name and --config-file to pass the environment variable set by the authenticate task.
    - script: |
        python -m twine upload -r testpypi --config-file $(PYPIRC_PATH) dist/textworld-*

- stage: Test_library
  variables:
  - name: installFromSource
    value: false
    readonly: true
  jobs:
  - template: linux-template.yml
    parameters:
      vmImages: [ 'ubuntu-18.04' ]
      pythonVersions: [ '3.7', '3.8' ]
  - template: linux-template.yml
    parameters:
      vmImages: [ 'ubuntu-20.04' ]
      pythonVersions: [ '3.7', '3.8' ]
  - template: macos-template.yml
    parameters:
      vmImages: [ 'macOS-10.14' ]
      pythonVersions: [ '3.6' ]
  - template: macos-template.yml
    parameters:
      vmImages: [ 'macOS-10.15' ]
      pythonVersions: [ '3.7' ]
      # pythonVersions: [ '3.8' ]  # For some reasons, chromedriver is failing.
